DATA  SEGMENT
STRINGl  DB 'Move the cursor backward.'
STRING2  DB 'Move the cursor backward.'
MESSl DB 'Match.',13,10,'$'
MESS2 DB 'NO Match!',13,10,'$'
DATA ENDS
PROG SEGMENT
ASSUME CS:PROG,DS:DATA,ES:DATA
START:MOV AX,DATA
MOV DS,AX
MOV ES,AX
LEA  SI,STRINGl
LEA  DI,STRING2
CLD
MOV CX,25
REPZ CMPSB
JZ MATCH
LEA DX,MESS2
JMP SHORT DISP
MATCH:   LEA DX,MESSl
DISP:     MOV AH,09
INT 21H
MOV AH,4CH
INT 21H
PROG ENDS
END START